// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo2fC88qI3Z9on8nitRiADb2vyA2WeLK8',
    appId: '1:592550022084:web:795b143c782832604eb291',
    messagingSenderId: '592550022084',
    projectId: 'duolingo-1dfff',
    authDomain: 'duolingo-1dfff.firebaseapp.com',
    storageBucket: 'duolingo-1dfff.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9FlaWAtNXbconymPUy2dMaTgdkHH_P3M',
    appId: '1:592550022084:android:e59ed337813462b74eb291',
    messagingSenderId: '592550022084',
    projectId: 'duolingo-1dfff',
    storageBucket: 'duolingo-1dfff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGbEIh5ws9n8AjKP-xkiDY54RoQRoqlnc',
    appId: '1:592550022084:ios:4fcf7f1611ab03064eb291',
    messagingSenderId: '592550022084',
    projectId: 'duolingo-1dfff',
    storageBucket: 'duolingo-1dfff.firebasestorage.app',
    iosBundleId: 'com.example.duolingo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGbEIh5ws9n8AjKP-xkiDY54RoQRoqlnc',
    appId: '1:592550022084:ios:4fcf7f1611ab03064eb291',
    messagingSenderId: '592550022084',
    projectId: 'duolingo-1dfff',
    storageBucket: 'duolingo-1dfff.firebasestorage.app',
    iosBundleId: 'com.example.duolingo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDo2fC88qI3Z9on8nitRiADb2vyA2WeLK8',
    appId: '1:592550022084:web:37612be5cdeac1504eb291',
    messagingSenderId: '592550022084',
    projectId: 'duolingo-1dfff',
    authDomain: 'duolingo-1dfff.firebaseapp.com',
    storageBucket: 'duolingo-1dfff.firebasestorage.app',
  );
}
