// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVOBN7pzGdgeWP956dg908ZA-mLMTNETs',
    appId: '1:433117123018:web:4202802398ae7b9bfa3f33',
    messagingSenderId: '433117123018',
    projectId: 'chat-965cd',
    authDomain: 'chat-965cd.firebaseapp.com',
    storageBucket: 'chat-965cd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-qHHkneAIva7iJH97_xFrcqIIhmP00cE',
    appId: '1:433117123018:android:597ec19dc336f575fa3f33',
    messagingSenderId: '433117123018',
    projectId: 'chat-965cd',
    storageBucket: 'chat-965cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxiXNQmn8swZBYMd99-uU3UZk1exn-9Bc',
    appId: '1:433117123018:ios:8b1e2fb18a90071efa3f33',
    messagingSenderId: '433117123018',
    projectId: 'chat-965cd',
    storageBucket: 'chat-965cd.firebasestorage.app',
    iosBundleId: 'com.example.duolingo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxiXNQmn8swZBYMd99-uU3UZk1exn-9Bc',
    appId: '1:433117123018:ios:8b1e2fb18a90071efa3f33',
    messagingSenderId: '433117123018',
    projectId: 'chat-965cd',
    storageBucket: 'chat-965cd.firebasestorage.app',
    iosBundleId: 'com.example.duolingo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVOBN7pzGdgeWP956dg908ZA-mLMTNETs',
    appId: '1:433117123018:web:04f2ce436422f0fdfa3f33',
    messagingSenderId: '433117123018',
    projectId: 'chat-965cd',
    authDomain: 'chat-965cd.firebaseapp.com',
    storageBucket: 'chat-965cd.firebasestorage.app',
  );
}
